version: "3.7"

networks:
  amp_frontend:
    name: amp_frontend
    driver: bridge
  amp_backend:
    name: amp_backend

services:
  php72:
    build: Setup/PHP/7.2
    container_name: amp_php72
    restart: always
    env_file: ./Setup/Configuration/environment.yml
    networks:
      - amp_backend
    volumes:
      - ./Setup/PHP/7.2/conf.d:/usr/local/etc/php/conf.d/
      - ./Setup/PHP/7.2/pool.d:/usr/local/etc/php-fpm.d/
      - ./Logs/:/var/log/
      - ./Projects/:/var/www/html/

  php73:
    build: Setup/PHP/7.3
    container_name: amp_php73
    restart: always
    env_file: ./Setup/Configuration/environment.yml
    networks:
      - amp_backend
    volumes:
      - ./Setup/PHP/7.3/conf.d:/usr/local/etc/php/conf.d/
      - ./Setup/PHP/7.3/pool.d:/usr/local/etc/php-fpm.d/
      - ./Logs/:/var/log/
      - ./Projects/:/var/www/html/

  apache:
    build: Setup/Apache
    container_name: amp_apache
    depends_on:
      - php72
      - php73
      - mariadb
    restart: always
    env_file: ./Setup/Configuration/environment.yml
    networks:
      - amp_frontend
      - amp_backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Setup/Apache/Config/vhosts/:/usr/local/apache2/conf/vhosts/
      - ./Logs/:/usr/local/apache2/logs/
      - ./Projects/:/usr/local/apache2/htdocs/

  mariadb:
    build: Setup/MariaDB
    container_name: db
    restart: always
    env_file: ./Setup/Configuration/environment.yml
    networks:
      - amp_backend
    ports:
      - "3306:3306"
    volumes:
      - ./Setup/MariaDB/Config/:/etc/mysql/conf.d/
      - ./Logs/:/var/log/mysql/
      - ./Databases/:/var/lib/mysql/
