version: "3.7"

networks:
  amp_frontend:
    name: amp_frontend
    driver: bridge
  amp_backend:
    name: amp_backend

services:
  php72:
    build: Setup/PHP/7.2
    container_name: amp_php72
    restart: always
    networks:
      - amp_backend
    environment:
      - PUID=66
      - PGID=66
      - TZ=Europe/Berlin
    volumes:
      - ./Setup/PHP/7.2/conf.d:/usr/local/etc/php/conf.d/
      - ./Setup/PHP/7.2/pool.d:/usr/local/etc/php-fpm.d/
      - ./Projects/:/var/www/html/
      - ./Logs/:/var/log/
  php73:
    build: Setup/PHP/7.3
    container_name: amp_php73
    restart: always
    networks:
      - amp_backend
    environment:
      - PUID=66
      - PGID=66
      - TZ=Europe/Berlin
    volumes:
      - ./Setup/PHP/7.3/conf.d:/usr/local/etc/php/conf.d/
      - ./Setup/PHP/7.3/pool.d:/usr/local/etc/php-fpm.d/
      - ./Projects/:/var/www/html/
      - ./Logs/:/var/log/

  apache:
    build: Setup/Apache
    container_name: amp_apache
    depends_on:
      - php72
      - php73
      - mysql
    restart: always
    networks:
      - amp_frontend
      - amp_backend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUID=66
      - PGID=66
      - TZ=Europe/Berlin
    volumes:
      - ./Setup/Apache/Config/vhosts/:/usr/local/apache2/conf/vhosts/
      - ./Projects/:/usr/local/apache2/htdocs/

  mysql:
    build: Setup/MariaDB
    container_name: amp_mariadb
    restart: always
    networks:
      - amp_backend
    environment:
      - PUID=66
      - PGID=66
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=r0otTes!
    volumes:
      - ./Databases/:/var/lib/mysql
