#######################################
# Environment Configuration
#  - feel free to edit -
# -> for most changes you only have to
#         docker-compose up -d
#    to apply them
#######################################
TZ=Europe/Berlin

#######################################
# MySQL settings
# -> if you change these settings
#    you have to remove the database:
#         docker-compose rm mysql
#    because it's stored database in
#    volume and provisioning is only
#    done once.
MYSQL_ROOT_PASSWORD=r0otTes!
MYSQL_USER=db
MYSQL_PASSWORD=db

#######################################
# PHP DEBUG
PHP_DEBUGGER=xdebug

#######################################
# TYPO3
TYPO3_CONTEXT=Development/Docker
